# Generated by Django 2.1.3 on 2019-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_pres_votes_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='parl_votes_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'parl_votes_counter',
            },
        ),
    ]
